volumes:
  postgres:

configs:
  adminer-index.php:
    content: |
      <?php
        if(!count($$_GET)) {
          $$_POST['auth'] = [
            'server' => $$_ENV['ADMINER_DEFAULT_SERVER'],
            'username' => $$_ENV['ADMINER_DEFAULT_USERNAME'],
            'password' => $$_ENV['ADMINER_DEFAULT_PASSWORD'],
            'driver' => $$_ENV['ADMINER_DEFAULT_DRIVER'],
            'db'    => $$_ENV['ADMINER_DEFAULT_DB'],
          ];
        }
        include './adminer.php';
      ?>

services:
  pusher:
    image: quay.io/soketi/soketi:1.0-16-alpine
    ports:
      - "6001:6001"
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: frumbers_backend
      POSTGRES_PASSWORD: password
      POSTGRES_DB: frumbers
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB: frumbers
      ADMINER_DEFAULT_USERNAME: frumbers_backend
      ADMINER_DEFAULT_PASSWORD: password
    restart: unless-stopped
    depends_on:
      - postgres
    configs:
      - source: adminer-index.php
        target: /var/www/html/index.php

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - adminer
      - pusher

  frumbers_backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    user: ${MY_UID}:${MY_GID}
    command: ["run", "--watch", "."]
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/app
    depends_on:
      - postgres
      - pusher
